apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - chat: frijugsincek/chat:2020-12-19-23-18-04
          name: chat
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://suleiman.db.elephantsql.com:5432/trchrzvw
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: trchrzvw
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chat-pass
                  key: KUMULUZEE_DATASOURCES0_IMAGES_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP


---


#apiVersion: v1
#kind: Service
#metadata:
#  name: chat
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 8080
#      protocol: TCP
#      targetPort: server
#  selector:
#    app: chat

apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  selector:
    app: chat
  ports:
    - name: web
      port: 8080
  type: ClusterIP